version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8338:8080"
    environment:
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: 3306 # Changed to 3306 for MySQL
      DB_USER: root
      DB_PASSWORD: ${SECRET_KEY?Variable SECRET_KEY is no set}
      DB_NAME: debt_helper
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: 6379
      GIN_MODE: ${GIN_MODE:-release}
      # Add other environment variables your app needs
    networks:
      - debt_helper_network

networks:
  debt_helper_network:
    driver: bridge